config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'static_pages#home'

  get '/about' => 'static_pages#about', as: 'about'

  get '/welcome' => 'static_pages#welcome', as: 'welcome'

  devise_for :users, controllers: {
        registrations: 'user/registrations'
      }

  resources :genres

  resources :songs

  resources :albums

  resources :artists

end

app/models/album.rb
class Album < ActiveRecord::Base
	belongs_to :genre
	belongs_to :artist
	has_many :songs

	validates :title, presence: true

	mount_uploader :cover, CoverUploader

	extend FriendlyId
  	friendly_id :title, use: :slugged
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.paginate(page: params[:page], per_page: 10)
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
    @artists = Artist.all
    @genres = Genre.all
  end

  # GET /albums/1/edit
  def edit
    @artists = Artist.all
    @genres = Genre.all
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:title, :genre_id, :artist_id, :cover)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<%= bootstrap_form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.collection_select :genre_id, @genres, :id, :name %>
  </div>
  <div class="field">
    <%= f.collection_select :artist_id, @artists, :id, :name %>
  </div>
  <div class="field">
    <%= f.file_field :cover %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/albums/edit.html.erb
<h1>Editing Album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<<p id="notice"><%= notice %></p>

<center>
  <h1>Albums</h1>
</center>


<div class="container">
  <div class="row">
    <% @albums.each do |album| %>
      <%= link_to image_tag(album.cover_url, class: 'col-md-3 index-album-cover'), album %>
    <% end %>
  </div>
  <br>
  <%= link_to 'New Album', new_album_path, class: 'btn btn-md btn-success' %>
</div>


<%= will_paginate @albums, renderer: BootstrapPagination::Rails %>

app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
	<div class="row">
		<%= image_tag(@album.cover_url, class: 'col-md-6') if @album.cover.present? %>
		<div class="col-md-6">
			<h1><%= @album.title %></h1>
			<h4><%= @album.artist.name %> | <%= @album.genre.name %></h4>
			<div class="panel panel-success">
			  <div class="panel-heading">
			    <h3 class="panel-title">Track Listing</h3>
			  </div>
			  <div class="panel-body">
			    <ol>
			    	<% @album.songs.each do |song| %>
			    	<li><%= link_to song.name, song_path(song) %></li>
			    	<% end %>
			    </ol>
			  </div>
			</div>
			<%= link_to 'Edit This Album', edit_album_path(@album) %>
		</div>
	</div>
</div>